### PR TITLE
Move hostname to last argument on Mac

### PR DESCRIPTION
**Pull request by JesseVermeulen123**
Closes https://github.com/dopecodez/pingman/issues/18

### CODE REVIEW

**Review by dopecodez — COMMENTED** [review]
The changes look good, did you try testing this on a mac machine? I'll plug in and test it on my mac tonight before merging these changes.

**Comment by JesseVermeulen123** [comment]
Hey, I'll test them quickly right now.

**Comment by JesseVermeulen123** [comment]
Both options from the README worked 🎉

**Comment by dopecodez** [comment]
I just tried it out too, looks good to me! 

Thanks for the PR, @JesseVermeulen123 🥇

**Pull request merged**
