### PR TITLE
fix: incorrect regex for handling short subdomains

### LINKED ISSUE #33: Throws IP_NOT_VALID error on short subdomains
When using short subdomains (E.G. `i.test.example.com`), calling `ping` will incorrectly throw an error with `Given IP address is not valid`.

Likely due to a too-strict regex in [`validateIp`](https://github.com/dopecodez/pingman/blob/master/src/helper.ts#L12).

Example:
```
try {
    await ping('i.test.example.com') // will throw "ipError: Given IP address is not valid"
}
catch(err) {
    console.error(err)
}
```

### PR DESCRIPTION
**Pull request by foxxyz**
* Changes the "IP validation" regex to correctly handle short subdomains (fixes #33)
 * Adds another test to verify handling of bare domains

Side note: I'd argue the domain validation regex should be even more liberal than it currently is - no reason to think the user is intentionally trying to pass in a bogus domain... and if they are, maybe just let the system CLI `ping` fail on it instead. Validating all possible domains via regex is a pain and probably pointless.

Regardless - thanks for the library! Let me know if you'd like additional changes.

### CODE REVIEW

**Comment by dopecodez** [comment]
You make a good point, @foxxyz . The way domains are changing it probably is a difficult task to validate every domain.

The purpose of the regex was to give the user more readable errors, so that they can check their urls and not think its a problem with ping. However, maybe we should ping anyways and throw a readable error. We can think about implementing this, I agree with your premise.

**Review by dopecodez — APPROVED** [review]

**Comment by foxxyz** [comment]
Thank you for the review @dopecodez! Do you need anything else from me to get this merged?

**Comment by dopecodez** [comment]
No, just got caught up yesterday and didn't get time to finish a release. Thanks for the PR, @foxxyz 🏅

**Comment by foxxyz** [comment]
Thank you and keep up the good work!

**Pull request merged**
